# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2      #Motor Mysql
  encoding: utf8       #Codificacion
  database: productos  #"Nombre de la base de datos"
  username: root       #Usuario de la base de datos
  password: root       #Password de la base de datios
  host: 127.0.0.1      #Servidor
  port: 3306           #Puerto
